image: node:8.11.3

pages:
  cache:
    paths:
    - node_modules/

  script:
  - yarn install
  - yarn run build
  - rm -r public/*
  - cp -r dist/* public
  - gzip -r public
  - cp -r dist/* public
  artifacts:
    paths:
    - public
  only:
  - master
