image: node:8.11.3

pages:
  cache:
    paths:
    - node_modules/

  script:
  - yarn install
  - yarn run build
  - rm public/*
  - rm dist/js/*.map
  - mv dist/* public
  artifacts:
    paths:
    - public
  only:
  - master